name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
    - release/*
  paths:
    include:
    - application/*

pool:
  vmImage: 'windows-latest'

steps:

# - pwsh: |
#     Get-ChildItem -Path $(Pipeline.Workspace) -Recurse -Depth 2
#     Get-ChildItem -Path Env:\
#   displayName: 'Very Useful'

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'

- task: AzureCLI@2
  displayName: 'DEV Deployment'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')
  inputs:
    azureSubscription: 'SPH-PIPELINE-RUNNER-NONPROD'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      . .\deployment\deploy.ps1
      Run-Deployment DEV
    addSpnToEnvironment: true

# add other environments...